Selenium Basic
참고 : https://goodthings4me.tistory.com/567

1. 로그인 버튼 클릭
>>> from selenium.webdriver.common.by import By

-> browser.find_element_by_class_name(“link_login”) 입력 시 오류 발생해 대체할 메서드 상용을 위해 By import

>>> elem = browser.find_elements(By.CLASS_NAME, "link_login")

>>> elem
[<selenium.webdriver.remote.webelement.WebElement (session="734b351e07889d26b459b6be2545874e", element="f1c9aac1-db35-424a-b2ac-a4e4a7e13c8e")>]

-> find_elements() 메서드를 사용해 리스트 형태가 출력

>>> elem.click()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'click'

>>> elem = browser.find_element(By.CLASS_NAME, "link_login")

>>> elem
<selenium.webdriver.remote.webelement.WebElement (session="734b351e07889d26b459b6be2545874e", element="f1c9aac1-db35-424a-b2ac-a4e4a7e13c8e")>

>>> elem.click()

>>> browser.back()

>>> browser.forward()

>>> browser.refresh()

>>> browser.back()

2. 검색어 입력

>>>elem = browser.find_element(By.ID, "query")

>>> elem
<selenium.webdriver.remote.webelement.WebElement (session="734b351e07889d26b459b6be2545874e", element="c2423655-a886-4f7b-912d-9bf7f6c8fdc8")>

>>> from selenium.webdriver.common.keys import Keys

>>> elem.send_keys("나도코딩”).
-> 검색어를 입력하는 경우에는, Keys 라이브러리 import 할 필요 X

>>> elem.send_keys(Keys.ENTER)
-> 검색어 입력 후 엔터 누르기

3. A 태그의 href 주소 전체 가져오기

>>> elem = browser.find_element(By.TAG_NAME, “a”)

>>> elem

>>> for e in elem:
              e.get_attribute(“href”)

3. XPATH 로 검색어 입력 및 검색

>>> browser.get("http://daum.net")

>>> elem = browser.find_element(By.NAME, "q")

>>> elem

<selenium.webdriver.remote.webelement.WebElement (session="734b351e07889d26b459b6be2545874e", element="c92acb3e-5be1-4774-a9b7-cad489ad6b65")>

>>> elem.send_keys("나도코딩")

>>> elem.send_keys(Keys.ENTER)

>>> browser.back()

>>> elem = browser.find_element(By.NAME, "q")

>>> elem.send_keys("나도코딩")

>>> elem = browser.find_element(By.XPATH, "//*[@id="daumSearch"]/fieldset/div/div/button[2]")
  File "<stdin>", line 1
    elem = browser.find_element(By.XPATH, "//*[@id="daumSearch"]/fieldset/div/div/button[2]")
                                                    ^
SyntaxError: invalid syntax

>>> elem = browser.find_element(By.XPATH, "//*[@id='daumSearch']/fieldset/div/div/button[2]")

-> 따옴표 처리 해주기

>>> elem

<selenium.webdriver.remote.webelement.WebElement (session="734b351e07889d26b459b6be2545874e", element="aadead3d-e5ef-4920-950b-996726822ff4")>

>>> elem.click()

4. 브라우저 종료

>>> browser.close()

-> 현재 열려있는 창만 닫음

>>> browser.quit()

-> 브라우저 전체 종료

[Selenium 관련 오류 및 해결 모음]

1. elem = browser.find_element_by_class_name("link_login")

      오류
- <stdin>:1: deprecationwarning: find_element_by_class_name is deprecated. please use find_element(by=by.class_name, value=name) instead

->   해결
      elem = browser.find_elements(By.CLASS_NAME, "link_login")

->  오류
      elem.click() 입력 시
      AttributeError: 'list' object has no attribute 'click’.

->  해결
      elements 와 element 차이로 인해 발생하는 에러
     -> elem = browser.find_element(By.CLASS_NAME, "link_login")